<?php

namespace Mbcs\MbcsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnergieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnergieRepository extends EntityRepository
{
}
